vim.keymap.set('n', '<C-e>', ':wq<cr>', { noremap = true, silent = true })
vim.keymap.set('n', '<C-y>', ':q!<cr>', { noremap = true, silent = true })
vim.keymap.set('n', '<C-cr>', function()
  local branch = vim.fn.FugitiveHead()
  vim.api.nvim_put({ branch .. ': ' }, 'c', true, true)
end, { buffer = true, noremap = true, silent = true })
