format = """
$nix_shell\
$docker_context\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$c\
$python\
$lua\
$rust\
$fill\
$cmd_duration $jobs $time\
$line_break\
$character"""

[fill]
symbol = " "

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"
min_time = 4
show_milliseconds = false
disabled = false

[time]
disabled = false
style = "bold white"
format = '\[[$time]($style)\]'

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow) '
trim_at = "."
disabled = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
# vicmd_symbol = "[❮](green)"

# configure directory
[directory]
read_only = " "
truncation_length = 10
truncate_to_repo = true    # truncates directory to root folder if in github repo
style = "bold italic blue"

[docker_context]
symbol = " "
format = '[\[$symbol$context\]](blue bold) '
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}Python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[rust]
symbol = " "

[nix_shell]
symbol = " "
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = '[\[$symbol$state( \($name\))\]](bold blue) '

[package]
symbol = "󰏗 "

[aws]
symbol = "  "

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[ruby]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[ocaml]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "

[zig]
symbol = " "

[os.symbols]
Amazon = " "
Android = " "
Arch = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Kali = " "
Linux = " "
Macos = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
